name: CI

on:
  push:
    branches: [ "main" , "develop", "feat/*"]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
  # rodando em um ubuntu 22 LST
    runs-on: ubuntu-22.04

# Passos
    steps:
    # passo 1: clonando repo
    - name: clonando repo
      uses: actions/checkout@v4

    # passo 2: configurando java
    - name: configurando java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    # passo 3: compilando projeto
    - name: compilando o projeto
      run: mvn clean package -DskipTests
